[target.thumbv6m-none-eabi]
linker = "rust-lld"
rustflags = ["-C", "link-arg=-Tlinker/rp2040/pico_demo.ld", "-C", "link-arg=--gc-sections"]

[target.thumbv8m.main-none-eabi]
linker = "rust-lld"
rustflags = ["-C", "link-arg=-Tlinker/rp2350/pico2w_demo.ld", "-C", "link-arg=--gc-sections"]
